# CPM Package Lock
# This file should be committed to version control

# fmt
CPMDeclarePackage(fmt
  NAME fmt
  VERSION 12.1.0
  GIT_TAG 12.1.0
  GITHUB_REPOSITORY fmtlib/fmt
  SYSTEM YES
  GIT_SHALLOW YES
  EXCLUDE_FROM_ALL YES
  OPTIONS
    "FMT_INSTALL YES"
  CUSTOM_CACHE_KEY 12.1.0 GIT_PROGRESS YES
)
# nlohmann_json
CPMDeclarePackage(nlohmann_json
  NAME nlohmann_json
  VERSION 3.11.3
  GIT_TAG v3.11.3
  GITHUB_REPOSITORY nlohmann/json
  SYSTEM YES
  GIT_SHALLOW YES
  EXCLUDE_FROM_ALL YES
  CUSTOM_CACHE_KEY 3.11.3 GIT_PROGRESS YES
)
# GTest
CPMDeclarePackage(GTest
  NAME GTest
  VERSION 1.15.2
  GIT_TAG v1.15.2
  GITHUB_REPOSITORY google/googletest
  SYSTEM YES
  GIT_SHALLOW YES
  EXCLUDE_FROM_ALL YES
  OPTIONS
    "INSTALL_GTEST OFF"
  CUSTOM_CACHE_KEY 1.15.2 GIT_PROGRESS YES
)
